[file_name_planet_population]
fyi_plot_name = /Users/eckhartspalding/Documents/git.repos/life_detectors/felix_yields/input/junk_20260206_sweep_diam_3_0_catalog_fyi_plot_F.png
file_name = /Users/eckhartspalding/Documents/git.repos/life_detectors/felix_yields/input/trunc_10_F_type_only_20260206_sweep_diam_3_0_catalog.txt


[dir_file_name_psg_spectra]
dir_name = /Users/eckhartspalding/Documents/git.repos/life_detectors/notebooks/sample_psg_config_files/
#dir_name = /Users/eckhartspalding/Documents/git.repos/life_detectors/notebooks/sample_psg_config_files_earth_10pc_only/
# directory containing the NASA PSG spectrum files

[lum_type]
O = 40000
B = 1000
A = 15
F = 3
G = 1
K = 0.4
M = 0.05
# bolometric L_sol
# approximate vals only