[observation]
qe_start = 0.4
qe_stop = 0.9
qe_step = 0.2

# n_int: number of integrations (start, stop, step size)
# qe: quantum efficiency (start, stop, step)
# note qe_stop is NOT included (values are made with np.arange(start, stop, step), so [start, ... stop))