[observation]
qe_start = 0.1
qe_stop = 1.1
qe_step = 0.1

# n_int: number of integrations (start, stop, step size)
# qe: quantum efficiency (start, stop, step)
# note qe_stop is NOT included (values are made with np.arange(start, stop, step), so [start, ... stop))